ExodusMovement/schemasafe

src/generate-function.js
Makes code a bit more clean, add an extra indent check that build() would fail on wrong `{` `}` balance (or if the balance was misdetected).
=> Minor cleanup + indent check at build()

LICENSE
I think this should be correct.
Last line touched because it was missing an EOL.
=> Update copyright and year

README.md, src/index.js
This reduces generated function lines of code by ~25% and makes them more readable in case when errors are not needed.
This should not give a performance benefit though, just leaner code presentation.
Depends on #39.
=> Inline return false on simple error handling

src/index.js
After #42.
Checking for `present()` twice makes no sense.
Also, now `{items:[{allOf:[{default:10}]}` fails with `useDefaults`, because defaults don't make any sense in nested checks.
`rule` and `subrule` moved below `present()` check because they now circumvent it when called on the current node, so we must be sure that those are not used before that check.
Only `dependencies/dependentRequired`, `not`, `if/then/else`, `allOf/anyOf/oneOf` can cause such nested checks -- i.e. anything that invokes `rule(current,` or `subrule(current, `.
=> Don't check for present() twice

src/index.js
Also use a self-documenting variable name.
=> Add more noop regexps

src/index.js
Needed by #29, forgot to commit earlier.
=> Expose original errors on the error thrown from parser

doc/Secure-code-generation.md
Depends on #47 
Linked complexity checks doc isn't here yet, I'll add those separately.
Given alpha version and docs being in progress, I think it's ok for that link to point there in advance.
=> doc: Secure code generation

src/index.js
This also fixes double 'return false' on includeErrors:
```js
require('.').validator({type:'object'},{includeErrors:true}).toModule()
```
This doesn't change the actual behavior.
=> Simplify error() function code

src/index.js, test/regressions/const-enum-strong.js
After #66 
Fixes: https://github.com/ExodusMovement/schemasafe/issues/63
=> Check const/enum before everything else, forbid other rules

src/index.js
Refs: https://github.com/ExodusMovement/schemasafe/pull/50#discussion_r443977304
=> jsonCheck and isJSON options have no sense in parser mode

src/index.js
`parent` is now not a name but an object pointing to the parent property structure.
This will allow to improve error handling later.
No actual behavior changes yet.
Refs: https://github.com/ExodusMovement/schemasafe/issues/56
Extracted from #20.
=> Use fully structured paths in propvar/propimm

src/index.js
This allows to force `allErrors = false` instead of `true` in `subrule()`.
Also simplifies the logic significantly, no more error counter restoring (and no more error counter).
=> Wrap subrule in iife

src/index.js
For now, this works only 'properies' rule that has a sibling 'required' rule, and only in `allErrors = false` mode.
In that case, we can be sure that some properties existence is already are checked by sibling `required` rule, so we don't have to re-check it in `properties` rule before doing further value validation.
This simplifies generated code for any `required` + `properties` combination which we'll use a lot.
=> Skip `property` existance check when validated by `required`

src/index.js
`unmodifiedPrototypes` option assumes that prototypes of Array and Object are not polluted at run time.
That allows to remove `hasOwnProperty` check when
1. looping over array indices, or
2. accessing literal properties that are not present on any built-in prototypes.
That gives a significant performance benefit in bechmark.
This is off by default and is needed to research speed implications of including hasOwn check, and to allow opt-in for increased performance in case of environments with known unmangled prototypes and/or safe schemas.
Best used in combination with isJSON.
=> Add unmodifiedPrototypes to skip non-prototype keywords hasOwn check

README.md
Let's make it clear that it's a pre-release for now.
=> doc: Add an npm version badge

test/misc.js
Refs: https://github.com/mafintosh/is-my-json-valid/pull/161
Co-authored-by: @bahmutov
Apparently, this just works here, because the code is much more robust ;-).
=> Add testcase from is-my-json-valid#161

src/index.js, test/regressions/unmodifiedPrototypes-class.js
Overlooked in #70 
Tests included.
=> unmodifiedPrototypes alone should not affect non-JSON classes

src/formats.js
Refs: https://tools.ietf.org/html/rfc1034#section-3.1
Tests will be introduced separately.
Note that email does not need this.
=> Fix support for dot-terminated hostnames

src/formats.js
Tests will come separately.
Other regexps do not miss `$`.
=> Fix email format

src/pointer.js
This allows to pass a sub-schema with a sub-schema having a fully resolved `$id`, which will be added as a new top-level schema.
This is not ideal as works only with full ids, but this makes the solution less complex.
This is supported only in cases where schemas are passed as an array for their ids to be extracted from the schemas themselves.
Also, this changes the behavior of #93 to support only fully resolved ids.
Tests will be introduced separately.
=> extract sub-schemas with fully resolved ids from all schemas

.github/workflows/nodejs.yml, README.md, codecov.yml, package.json
No access token needed for public repos.
=> Test coverage on CI and upload to Codecov

src/index.js, test/regressions/contains-errors.js
Also fix sub-error paths for oneOf and anyOf.
Depends on #111.
=> Extract sub-errors from oneOf/anyOf/contains on failure

src/index.js, src/known-keywords.js, test/json-schema.js
=> Implement $recursiveRef and $recursiveAnchor

README.md
=> Use npmjs package name for import

doc/samples/draft-next/refRemote.md, doc/samples/draft2019-09/refRemote.md, doc/samples/draft2020-12/refRemote.md, doc/samples/draft4/refRemote.md, doc/samples/draft6/refRemote.md, doc/samples/draft7/refRemote.md
I need this as a separate commit/PR to not pollute the next one.
This is just a result of a previous testsuite update in d0cbcb93e4f075ff47245428e7541ba53eb15836 where refs locations changed.
=> doc: update generated testsuite samples
