ExodusMovement/schemasafe

src/index.js
Use a single structured cache instead of separate syms
Improves code readability.
---
Cache patterns per-scope, not per-schema
This should remove needless duplication of equivalent patterns when they
are referenced from different schemas via refs.
Also use a Map there.
=> Cleaner impl of per-scope variable cache

src/index.js, test/parser.js
Enforces at least one of `format` or `pattern` to be present on strings.
Enabled by default in strong mode.
Opt-out is possible via no-op regex as `pattern`, i.e. `^[\s\S]*$`.
No-op regex is specifically excluded from the generated code (as it always passes).
=> Implement requireStringValidation

README.md, src/index.js
1. Simplify type validation `else {}` wrap
This makes code generate `}\n else {` instead of `} else {` on type check, but it makes the generator logic easier.
2. Unwrap `else{}` if type validation returned early
If `allErrors` is false, type validation always returns on failed type check.
In that case, we don't need to wrap code under it in `else { }`.
3. Generated toModule() result in Readme updated accordingly.
=> Simplify type validation

src/index.js, test/misc.js
It's disabled by default as it's assumed that all data comes from `JSON.parse`.
Could be useful otherwise to guarantee that input is JSON-compatible.
=> add jsonCheck option

src/index.js
Avoids generating useless empty `if (!undefined) {}` blocks.
E.g. on JSON Schema draft6 schema:
```diff
26,27d25
<     if (data["default"] !== undefined && hasOwn(data, "default")) {
<     }
30,33d27
<       for (let i = 0; i < data["examples"].length; i++) {
<         if (data["examples"][i] !== undefined && hasOwn(data["examples"], i)) {
<         }
<       }
159,160d152
<     }
<     if (data["const"] !== undefined && hasOwn(data, "const")) {
```
=> Fast track empty schema nodes

src/index.js
```
Fix keyval check in present()
It might be 0 in arrays.
```
```
Fast-track top-level boolean false
This allows to harden present() check.
```
Due to this check being slow (and done twice in some edge cases), I will introduce some exceptions there after this PR lands.
This is why code is currently organized that way -- i.e. separate branches for `keyname` and `keyval`.
=> Harden present() check

src/index.js
Just do that for code consistency, no actual improvement, as unlike other places, this block can't be empty and excluded.
=> Use fun.block() in one more place

src/index.js
After #44.
Due to the size of generated code, this should be in fact more readable, as it keeps the number of lines smaller and keeps one logical operation on a single line.
Also fix code style for one boolean check.
=> Inline errors restore in contains/not/oneOf

.eslintrc.json, src/safe-format.js
In pre-ES2019, those are not suitable for inserting in JS context.
This should affect Node.js 8 and below.
Refs: https://v8.dev/features/subsume-json
=> Post-process JSON.stringify to escape u2028 and u2029

src/index.js, test/options.js
Supports only `additionalProperties: false` and `additionalItems: false`.
Closes: https://github.com/ExodusMovement/schemasafe/issues/55
=> Implement removeAdditonal

src/index.js, src/pointer.js, test/misc.js, test/schema-path.js
1. Always return pointer as an URI fragment for consistency
2. Drop `.type` in verboseErrors
3. Always include schemaPath in errors
=> Minor error handling fixes

src/jaystring.js, src/safe-format.js
After #46.
Otherwise wrong stringification can happen on Node.js 10 and below.
Demo (for old behavior): `console.log(String(new RegExp('\n')))`.
=> Stringify regex to new RegExp(...)

src/index.js
Note that it still comes with a 10x slowdown.
It's recommended to use parser API instead.
Fixes: https://github.com/ExodusMovement/schemasafe/issues/49
=> Ensure that jsonCheck is performed only once, at top level

src/index.js
Upd: depends on #59.
`Object.keys` are already present on the object itself, and can't be undefined because of JSON.
Also skip `hasOwn` check for `Object.keys` in non-JSON mode, leave only undefined check.
=> In json-only mode, don't check object keys for existance

doc/Secure-code-generation.md, src/safe-format.js, test/regressions/proto-jsval.js
Refs: https://www.ecma-international.org/ecma-262/#sec-json.parse
Refs: https://www.ecma-international.org/ecma-262/#sec-__proto__-property-names-in-object-initializers
Tests and documentation with the explanation included.
While I can't directly see how those can harm outside of `useDefaults` and bugs in whatever code consumed those defaults, it still breaks expectations around `jsval()`.
=> fix: Properly encode `__proto__` in jsval()

src/index.js, test/complexity.js, test/json-schema.js
No reason to use it, it is just confusing.
ajv does not support it, for example.
Simplifies some logic before fixing #63
=> Drop draft3-specific 'any' type

src/index.js, test/regressions/requireValidation-allOf.js
Fixes: https://github.com/ExodusMovement/schemasafe/issues/64
Depends on #67.
=> Fix requireValidation for oneOf/anyOf/allOf

README.md, src/index.js, src/pointer.js, src/scope-functions.js, test/data-path.js, test/misc.js
To unbreak `field` property in errors.
Also, `field` is renamed to `dataPath`.
Also, fixes `value`.
This only applies to `verboseErrors`.
Before: `{ field: 'data[favoriteSingleDigitWholeNumbers][j]' }`
After: `{ dataPath: '#/favoriteSingleDigitWholeNumbers/2' }`
=> verboseErrors handling improvements

src/index.js
1) Don't double-check parent for existance
2) Throw on keyval = 0 && keyname specified (unreachable safeguard)
=> Minor buildName() fixes

src/formats.js
I'm pretty sure `rgb(1%1%1%,...` is invalid.
=> formats: fix 'color' extra format

src/index.js
Overlooked in 498f55f54756d061ab2ca6da06c475e71cbf623a
Refs: https://github.com/ExodusMovement/schemasafe/pull/73
Refs: https://github.com/ExodusMovement/schemasafe/commit/498f55f54756d061ab2ca6da06c475e71cbf623a#diff-1fdf421c05c1140f6d71444ea2b27638L575
=> fix: use correct error path in 'contains'

src/index.js, test/complexity.js
E.g. `/^(a|aa)*$/` and `/^(aa?)*$/` also cause ReDoS, so warn users about them in strong mode.
Tests included.
=> Make regex complexity checks more paranoid

doc/Error-handling.md, src/index.js, test/regressions/allErrors-dos.js
This skips complex checks if corresponding length restrictions have already failed.
E.g., now included tests do not case a DoS even when `allErrors` is set to true.
Ensuring that schema limits that still requires `complexityChecks` (on by default in `strong` mode).
Best reviewed with hidden whitespace changes, as this involved indentation changes due to a wrapping block.
=> Make allErrors not a DoS vector

src/index.js, test/regressions/compile-errors.js
Before, it threw with `Cannot convert undefined or null to object` in some cases.
Now, all non-object invalid schemas produce `Schema is not an object` error.
Tests included.
No actual behavior change except for the clarified error message.
=> Cleaner error message on undefined nodes

src/pointer.js
Similar to line 70 of the same file: https://github.com/ExodusMovement/schemasafe/pull/91/files#diff-8aba63a34e9613927ab97bbc39471c29R70
Tests will come separately.
=> pointer: fix objpath2path conversion on 'id' properties

src/pointer.js
That might be needed if the top-level `$id` induced an origin change.
Tests will come separately.
=> pointer: include top-level $id in full objpath refs

src/index.js, src/pointer.js, test/json-schema.js
This allows specifying a list of schemas as an Array instead of an object, which should make consuming easier.
Schema identifiers are taken from `$id` properties in that case.
=> Store schemas in a Map, accept object/map/array

src/generate-function.js, src/index.js, src/safe-format.js
Actually, two loosely related changes here.
1) `obj.x` -> `obj["x"]` for properties with names `/^[a-z][a-z0-9_]*$/i`.
Note how this check is much less complex than what is-my-json-valid had (which attempted to inline _all_ valid property literals, so the regex was quite big). Approach in this PR should be trivial and safe.
Motivation: to make the generated code a bit more readable.
I expect that most properties will fit into that regexp.
2) As `safe()` ids now extended to case-insensitive, we can use it to wrap scope keys in `generate-function`, which double-checks that scope keys are safe for inclusion.
=> Use obj.x instead of obj["x"] in common safe cases

src/index.js, src/known-keywords.js, test/json-schema.js
`dependentSchemas` and `dependentRequired` behave like two branches of `dependencies` from pre-`draft2019-09` spec versions.
Also add a check that `dependentRequired` entries are not schemas but are arrays.
Most changes are whitespace due to extra indentation level.
We might want to push `draft2019-09` due to `unevaluatedProperties`, which _will_ make things easier if implemented.
=> Add dependentSchemas support from draft2019-09

src/formats.js
Also no need for the length check this way.
Tests will be introduced with updated JSON Schema Test Suite.
=> formats: use a simple non-nested regexp for uuids

.github/workflows/coverage.yml, .github/workflows/nodejs.yml, package.json
This way we won't try to run coverage on the whole matrix.
=> ci: test on 14.x, use a separate workflow for coverage

src/index.js
This allows us to add top-level preparation separately, instead of repeating it on every subschema ref compilation or having to use hacks to exclude preparation code from re-running.
I.e. buildSchemas is now called only once, and json check is now explicitly moved to a wrapping function.
That will likely be used to add some other common preparation steps that we will need to run only at top-level.
Makes all schemas be compiled with the exact same option set (as cleanup is now done outside of `compile`), otherwise things could have been bad in case of complex references between schemas.
This also comes with `error()` function cleanup as `jsonCheck` doesn't use it anymore, which gives a ~10x speedup on `verboseErrors` (without `jsonCheck`).
=> Split validator() from compile()

README.md, doc/Error-handling.md, src/index.js, src/scope-functions.js, test/data-path.js, test/misc.js, test/schema-path.js
Depends on #110.
Can be done now with a speedup of `dataPath` from #110 and this PR.
=> Enable dataPath in all errors, rename verboseErrors to reflectErrorsValue

src/index.js
Our checks below work correctly with `undefined`, a lot has changed since `is-my-json-valid`.
=> Remove useless null coercion

src/jaystring.js, test/jaystring.js
Regexp format tests will be added separately, to safe-format.
=> Normalize jaystring error messages, add tests

README.md, src/index.js, test/regressions/broken-required.js
Also rename `errors` internal variable to `errorCount` to avoid confusion, and avoid defining it needlessly when `allErrors !== true`.
Strict mode prevents from accidentally defining global variables, so this is secure and we won't slip in unnoticed `allErrors` usage without definition.
Depends on #112.
=> allErrors requires includeErrors

src/index.js, test/parser.js
If full errors are needed (and enabled), they can be accessed via the the `errors` property, as documented.
No reason to attempt to format all of them into the error message, that was both not pretty and broken, as 'message' was removed and those didn't include `dataPath`.
Also don't set undefined `errors` if errors are not enabled.
Tests included.
Example error messages (one per line):
* `JSON validation failed for type at #`
* `JSON validation failed for required at #/foo`
* `JSON validation failed for const at #/foo`
* `JSON validation failed for additionalProperties at #/abc`
Only the first error is embedded into the error message now, others are accessible via `errors` property (if enabled).
=> parser: embed first error in concise form if errors are enabled

src/index.js, src/scope-functions.js
Also cleaner code for `compare()`.
Also optimize `stringLength` and avoid using arrays when `.length` fails restriction.
Inline check ensures that we don't create arrays out of too large strings that are far above the `maxLength` restriction.
=> Use deepEqual only when needed, optimize multipleOf and maxLength

src/index.js, src/scope-functions.js
Gives about +10% with `includeErrors` option.
Does not change the produced code if `includeErrors` is disabled.
Depends on #113.
=> Optimize includeErrors=true more via buildName() inlining

doc/Error-handling.md, src/index.js, src/scope-functions.js, test/ref-errors.js
This approach is completely different from what ajv does.
This sees "through" `$ref`s, building full error references from the top, and descending into refs like `/something/$ref/path/continues` instead of replacing the whole path with the path where the reference resolves to.
This way, it is actually possible to tell where the error originated from, unlike with ajv which makes it hard to understand which schema caused the error in some situations.
Fixes most of #56. `oneOf` (and similar) tbd.
=> Make errors from $ref validation transparent

src/index.js
Groups common for-of iterations with `sub` creation.
Might later optimize `patternTest` and `forObjectKeys`.
=> Minor code style cleanup and grouping

README.md, doc/Auditable.md, doc/Specification-support.md, doc/samples/README.md, doc/samples/unevaluatedItems.md, doc/samples/unevaluatedProperties.md, src/compile.js, src/scope-functions.js, src/tracing.js, test/json-schema.js
~Depends on a bunch of other PRs.~
Static `unevaluatedItems` / `unevaluatedProperties` already landed to master and [28 out of 34](https://github.com/ExodusMovement/schemasafe/tree/master/doc/samples) tests work on that, with the remaining safely refusing to compile (as dynamic tracing is not enabled yet in master).
This PR adds support for dynamic tracing so that everything will work.
Draft for now.
=> Add dynamic unevaluatedItems and unevaluatedProperties support

test/extra-tests/ref.383.json
This adds test cases to demonstrate #138 
I am not really sure where to start fixing this. It is important to note that the case using draft 2019-09 passes, while it fails when using draft 07.
If there is any direction you can point me to, I will try to fix this.
=> tests: add failing test case

README.md, src/compile.js, test/options.js
Hi!
I was updating the TypeScript tsconfig JSON schema ( https://github.com/SchemaStore/schemastore/pull/1534/ ) and hit this case where `allowUnusedKeywords` wasn't being respected, I'm sorry for the size of the test, but I don't have enough experience writing schemas to know if a terser one is possible.
=> Support unused options in const or enums

index.d.ts
... not a `boolean` (in Draft 04 and above).
=> fix: typescript types - required is a string array

yarn.lock
A vulnerability was found in the minimatch. This flaw allows a Regular Expression Denial of Service (ReDoS) when calling the braceExpand function with specific arguments, resulting in a Denial of Service.
CVE-2022-3517
[CWE-400](https://cwe.mitre.org/data/definitions/400.html)
`CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H`
=> Fixed CVE-2022-3517

README.md, doc/Linter.md, doc/Options.md, index.d.ts, src/compile.js, src/index.js
Usage example:
```cjs
const { validator } = require('@exodus/schemasafe')
const fs = require('fs')
const path = require('path')
const dir = 'schemas/json'
const files = fs.readdirSync(dir).sort().map(x => path.join(dir, x))
const schemas = files.map(x => [x, JSON.parse(fs.readFileSync(x, 'utf-8'))])
for (const [name, schema] of schemas) {
try {
//validator(schema, { requireValidation: true  })
const errors = validator(schema, { lint: true })
for (const e of errors) {
console.log(name, ': ', e.message)
}
} catch (e) {
console.log(name, ': ', e)
}
}
```
=> feat: experimental linter mode

doc/samples/draft-next/anchor.md, doc/samples/draft-next/dynamicRef.md, doc/samples/draft-next/id.md, doc/samples/draft-next/items.md, doc/samples/draft-next/ref.md, doc/samples/draft2019-09/anchor.md, doc/samples/draft2019-09/id.md, doc/samples/draft2019-09/items.md, doc/samples/draft2019-09/ref.md, doc/samples/draft2020-12/anchor.md, doc/samples/draft2020-12/dynamicRef.md, doc/samples/draft2020-12/id.md, doc/samples/draft2020-12/items.md, doc/samples/draft2020-12/ref.md, doc/samples/draft4/id.md, doc/samples/draft4/items.md, doc/samples/draft4/ref.md, doc/samples/draft6/id.md, doc/samples/draft6/items.md, doc/samples/draft6/ref.md, doc/samples/draft7/id.md, doc/samples/draft7/items.md, doc/samples/draft7/ref.md, src/compile.js, test/regressions/strong-refs.js
Refs: https://github.com/ExodusMovement/schemasafe/issues/161#issuecomment-1670111982
This will allow e.g. this to compile in strong mode:
```js
{
$schema: 'https://json-schema.org/draft/2020-12/schema',
allOf: [
{
$ref: '#/definitions/base',
},
],
definitions: {
base: {
required: [],
properties: {
version: {
const: '2',
},
},
type: 'object',
//  unevaluatedProperties: false,
},
},
properties: {
type: {
const: 'acknowledge',
},
},
required: ['type'],
type: 'object',
unevaluatedProperties: false,
}
```
=> feat: don't require full top-level validation in non-cyclic-non-top-level refs

.github/CODEOWNERS
Setup a codeowners file as a prerequisite for #166.
Doc: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners
=> chore: add CODEOWNERS config

src/compile.js, test/regressions/177.js
Type delta calculation here is needed for discriminator to be sure that we can compile.
Fixes: #176. 
This is just the first part of the fix that will work if `type: object` is specified on levels 1 and 2 or level 3.
An additional fix is needed to allow specifying `type: object` only once on level 1.
See also explanation in https://github.com/ExodusMovement/schemasafe/issues/176#issuecomment-1910259508
=> fix: we are sure about type if parent checked it
